export const AVAILABLE_HOUR_REQUEST = 'AVAILABLE_HOUR_REQUEST';
export const AVAILABLE_HOUR_SUCCESS = 'AVAILABLE_HOUR_SUCCESS';
export const AVAILABLE_HOUR_FAIL = 'AVAILABLE_HOUR_FAIL';

export const TOGGLE_SELECTED_HOUR = 'TOGGLE_SELECTED_HOUR';

export const SET_AVAILABLE_HOUR_DATE = 'SET_AVAILABLE_HOUR_DATE';
