export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';
export const BOOKING_STATUS_RESET = 'BOOKING_STATUS_RESET';

export const USER_BOOKINGS_REQUEST = 'USER_BOOKINGS_REQUEST';
export const USER_BOOKINGS_SUCCESS = 'USER_BOOKINGS_SUCCESS';
export const USER_BOOKINGS_FAIL = 'USER_BOOKINGS_FAIL';
export const USER_BOOKINGS_RESET = 'USER_BOOKINGS_RESET';
